In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

plt.rcParams['font.sans-serif'] = ['SimHei', 'DejaVu Sans']
plt.rcParams['axes.unicode_minus'] = False

In [3]:
df = pd.read_excel('学生成绩汇总表.xlsx')
df

      姓名  语文    数学  英语  物理    化学  生物
0   学生 1  85  92.0  88  90  87.0  89
1   学生 2  72  65.0  70  68  66.0  71
2   学生 3  90  95.0  93  94  91.0  92
3   学生 4  68  70.0  65  66  63.0  67
4   学生 5  78   NaN  80  81  79.0  83
5   学生 6  55  60.0  58  56  59.0  57
6   学生 7  82  86.0  84  85   NaN  87
7   学生 8  75  73.0  77  74  76.0  72
8   学生 9  62  66.0  64  65  63.0  67
9  学生 10  88  90.0  89  91  88.0  90

In [4]:
df1 = df.drop(columns=[df.columns[0]])
df1

   语文    数学  英语  物理    化学  生物
0  85  92.0  88  90  87.0  89
1  72  65.0  70  68  66.0  71
2  90  95.0  93  94  91.0  92
3  68  70.0  65  66  63.0  67
4  78   NaN  80  81  79.0  83
5  55  60.0  58  56  59.0  57
6  82  86.0  84  85   NaN  87
7  75  73.0  77  74  76.0  72
8  62  66.0  64  65  63.0  67
9  88  90.0  89  91  88.0  90

In [6]:
imputer = SimpleImputer(strategy='mean')

In [7]:
df2 = pd.DataFrame(imputer.fit_transform(df1), columns=df1.columns)
df2

     语文         数学    英语    物理         化学    生物
0  85.0  92.000000  88.0  90.0  87.000000  89.0
1  72.0  65.000000  70.0  68.0  66.000000  71.0
2  90.0  95.000000  93.0  94.0  91.000000  92.0
3  68.0  70.000000  65.0  66.0  63.000000  67.0
4  78.0  77.444444  80.0  81.0  79.000000  83.0
5  55.0  60.000000  58.0  56.0  59.000000  57.0
6  82.0  86.000000  84.0  85.0  74.666667  87.0
7  75.0  73.000000  77.0  74.0  76.000000  72.0
8  62.0  66.000000  64.0  65.0  63.000000  67.0
9  88.0  90.000000  89.0  91.0  88.000000  90.0

In [9]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(df2)

pca = PCA(n_components=3)
X_pca = pca.fit_transform(X_scaled)

In [11]:
kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
labels = kmeans.fit_predict(X_pca)

D:\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

In [12]:
scaler=StandardScaler()

In [14]:
scalered_data=scaler.fit_transform(df2)

In [15]:
scalered_data

array([[ 0.87584578,  1.22310315,  0.98170104,  1.05098771,  1.12121212,
         0.99624059],
       [-0.32268002, -1.04570651, -0.59603278, -0.72760688, -0.78787879,
        -0.56309251],
       [ 1.33681724,  1.47519311,  1.41996044,  1.37436854,  1.48484848,
         1.25612944],
       [-0.69145719, -0.62555657, -1.03429217, -0.88929729, -1.06060606,
        -0.90961097],
       [ 0.23048573,  0.        ,  0.28048601,  0.32338083,  0.39393939,
         0.47646289],
       [-1.88998299, -1.46585644, -1.64785532, -1.69774938, -1.42424242,
        -1.77590714],
       [ 0.5992629 ,  0.71892322,  0.63109353,  0.64676167,  0.        ,
         0.82298136],
       [-0.04609715, -0.37346661,  0.01753038, -0.24253563,  0.12121212,
        -0.47646289],
       [-1.24462294, -0.96167652, -1.12194405, -0.9701425 , -1.06060606,
        -0.90961097],
       [ 1.15242865,  1.05504317,  1.06935292,  1.13183292,  1.21212121,
         1.0828702 ]])

In [20]:
kmeans = KMeans (n_clusters=2, random_state=0, max_iter=500)

In [21]:
kmeans.fit(scalered_data)

D:\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1419: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

KMeans(max_iter=500, n_clusters=2, random_state=0)

In [22]:
c = kmeans.labels_
c

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1], dtype=int32)

In [23]:
v= pd.Series(c,index=df['姓名'])
v

姓名
学生 1     1
学生 2     0
学生 3     1
学生 4     0
学生 5     1
学生 6     0
学生 7     1
学生 8     1
学生 9     0
学生 10    1
dtype: int32